<?php

namespace Config;

use CodeIgniter\Shield\Config\AuthGroups as ShieldGroups;

class AuthGroups extends ShieldGroups
{
  /**
   * --------------------------------------------------------------------
   * Default Group
   * --------------------------------------------------------------------
   * The group that a newly registered user is added to.
   */
  public string $defaultGroup = 'user';

  /**
   * --------------------------------------------------------------------
   * Groups
   * --------------------------------------------------------------------
   * The available authentication systems, listed
   * with alias and class name. These can be referenced
   * by alias in the auth helper:
   *      auth('api')->attempt($credentials);
   */
  public array $groups = [
    'superadmin' => [
      'title'       => 'Super Admin',
      'description' => 'Complete control of the site.',
    ],
    'admin' => [
      'title'       => 'Admin',
      'description' => 'Day to day administrators of the site.',
    ],
    'developer' => [
      'title'       => 'Developer',
      'description' => 'Site programmers.',
    ],
    'user' => [
      'title'       => 'User',
      'description' => 'General users of the site. Often customers.',
    ],
    'beta' => [
      'title'       => 'Beta User',
      'description' => 'Has access to beta-level features.',
    ],
  ];

  /**
   * --------------------------------------------------------------------
   * Permissions
   * --------------------------------------------------------------------
   * The available permissions in the system. Each system is defined
   * where the key is the
   *
   * If a permission is not listed here it cannot be used.
   */
  public array $permissions = [
    'admin.access'        => 'Can access the sites admin area',
    'admin.settings'      => 'Can access the main site settings',
    'groups.settings'     => 'Can access the groups settings',
    'groups.edit'         => 'Can edit existing user groups',
    'users.list'          => 'Can view a list of users in the system',
    'users.manage-admins' => 'Can manage other admins',
    'users.view'          => 'Can view user details',
    'users.create'        => 'Can create new non-admin users',
    'users.edit'          => 'Can edit existing non-admin users',
    'users.delete'        => 'Can delete existing non-admin users',
    'users.settings'      => 'Can manage User settings in admin area',
    'beta.access'         => 'Can access beta-level features',
    'site.viewOffline'    => 'Can view the site even when in "offline" mode',
    'widgets.settings'    => 'Can view the settings for site Widgets',
    'consent.settings'    => 'Can view the settings for the Consent module',
    'recycler.view'       => 'Can view the Recycler area',
    'logs.view'           => 'Can view the logs',
    'logs.manage'         => 'Can manage the logs',
    'me.edit'             => 'Can edit user\'s own settings',
    'me.security'         => 'Can change user\'s own password',


    'blogs.view'          => 'Can view pages details',
    'blogs.create'        => 'Can create new pages',
    'blogs.edit'          => 'Can edit existing pages',
    'blogs.delete'        => 'Can delete existing pages',
    'blogs.settings'      => 'Can manage pages settings in admin area',

    'pages.view'          => 'Can view pages details',
    'pages.create'        => 'Can create new pages',
    'pages.edit'          => 'Can edit existing pages',
    'pages.delete'        => 'Can delete existing pages',
    'pages.settings'      => 'Can manage pages settings in admin area',

    'downloads.view'          => 'Can view pages details',
    'downloads.create'        => 'Can create new pages',
    'downloads.edit'          => 'Can edit existing pages',
    'downloads.delete'        => 'Can delete existing pages',
    'downloads.settings'      => 'Can manage pages settings in admin area',

    'galleries.view'          => 'Can view pages details',
    'galleries.create'        => 'Can create new pages',
    'galleries.edit'          => 'Can edit existing pages',
    'galleries.delete'        => 'Can delete existing pages',
    'galleries.settings'      => 'Can manage pages settings in admin area',

    'sejarah.view'          => 'Can view pages details',
    'sejarah.create'        => 'Can create new pages',
    'sejarah.edit'          => 'Can edit existing pages',
    'sejarah.delete'        => 'Can delete existing pages',
    'sejarah.settings'      => 'Can manage pages settings in admin area',

    'visimisi.view'          => 'Can view pages details',
    'visimisi.create'        => 'Can create new pages',
    'visimisi.edit'          => 'Can edit existing pages',
    'visimisi.delete'        => 'Can delete existing pages',
    'visimisi.settings'      => 'Can manage pages settings in admin area',

    'motto.view'          => 'Can view pages details',
    'motto.create'        => 'Can create new pages',
    'motto.edit'          => 'Can edit existing pages',
    'motto.delete'        => 'Can delete existing pages',
    'motto.settings'      => 'Can manage pages settings in admin area',

    'prestasi.view'          => 'Can view pages details',
    'prestasi.create'        => 'Can create new pages',
    'prestasi.edit'          => 'Can edit existing pages',
    'prestasi.delete'        => 'Can delete existing pages',
    'prestasi.settings'      => 'Can manage pages settings in admin area',

    'tupoksi.view'          => 'Can view pages details',
    'tupoksi.create'        => 'Can create new pages',
    'tupoksi.edit'          => 'Can edit existing pages',
    'tupoksi.delete'        => 'Can delete existing pages',
    'tupoksi.settings'      => 'Can manage pages settings in admin area',

    'alurpelayanan.view'          => 'Can view pages details',
    'alurpelayanan.create'        => 'Can create new pages',
    'alurpelayanan.edit'          => 'Can edit existing pages',
    'alurpelayanan.delete'        => 'Can delete existing pages',
    'alurpelayanan.settings'      => 'Can manage pages settings in admin area',

    'maklumatpelayanan.view'          => 'Can view pages details',
    'maklumatpelayanan.create'        => 'Can create new pages',
    'maklumatpelayanan.edit'          => 'Can edit existing pages',
    'maklumatpelayanan.delete'        => 'Can delete existing pages',
    'maklumatpelayanan.settings'      => 'Can manage pages settings in admin area',

    'komitmenbersama.view'          => 'Can view pages details',
    'komitmenbersama.create'        => 'Can create new pages',
    'komitmenbersama.edit'          => 'Can edit existing pages',
    'komitmenbersama.delete'        => 'Can delete existing pages',
    'komitmenbersama.settings'      => 'Can manage pages settings in admin area',

    'kebijakanmutu.view'          => 'Can view pages details',
    'kebijakanmutu.create'        => 'Can create new pages',
    'kebijakanmutu.edit'          => 'Can edit existing pages',
    'kebijakanmutu.delete'        => 'Can delete existing pages',
    'kebijakanmutu.settings'      => 'Can manage pages settings in admin area',

    'komitmenketerbukaan.view'          => 'Can view pages details',
    'komitmenketerbukaan.create'        => 'Can create new pages',
    'komitmenketerbukaan.edit'          => 'Can edit existing pages',
    'komitmenketerbukaan.delete'        => 'Can delete existing pages',
    'komitmenketerbukaan.settings'      => 'Can manage pages settings in admin area',

    'standarmutu.view'          => 'Can view pages details',
    'standarmutu.create'        => 'Can create new pages',
    'standarmutu.edit'          => 'Can edit existing pages',
    'standarmutu.delete'        => 'Can delete existing pages',
    'standarmutu.settings'      => 'Can manage pages settings in admin area',

    'datapegawai.view'          => 'Can view pages details',
    'datapegawai.create'        => 'Can create new pages',
    'datapegawai.edit'          => 'Can edit existing pages',
    'datapegawai.delete'        => 'Can delete existing pages',
    'datapegawai.settings'      => 'Can manage pages settings in admin area',

    'pejabatstruktural.view'          => 'Can view pages details',
    'pejabatstruktural.create'        => 'Can create new pages',
    'pejabatstruktural.edit'          => 'Can edit existing pages',
    'pejabatstruktural.delete'        => 'Can delete existing pages',
    'pejabatstruktural.settings'      => 'Can manage pages settings in admin area',

    'strukturorganisasi.view'          => 'Can view pages details',
    'strukturorganisasi.create'        => 'Can create new pages',
    'strukturorganisasi.edit'          => 'Can edit existing pages',
    'strukturorganisasi.delete'        => 'Can delete existing pages',
    'strukturorganisasi.settings'      => 'Can manage pages settings in admin area',

    'patologi.view'          => 'Can view pages details',
    'patologi.create'        => 'Can create new pages',
    'patologi.edit'          => 'Can edit existing pages',
    'patologi.delete'        => 'Can delete existing pages',
    'patologi.settings'      => 'Can manage pages settings in admin area',

    'virologi.view' => 'Can view pages details',
    'virologi.create' => 'Can create new pages',
    'virologi.edit' => 'Can edit existing pages',
    'virologi.delete' => 'Can delete existing pages',
    'virologi.settings' => 'Can manage pages settings in admin area',
    'parasitologi.view' => 'Can view pages details',
    'parasitologi.create' => 'Can create new pages',
    'parasitologi.edit' => 'Can edit existing pages',
    'parasitologi.delete' => 'Can delete existing pages',
    'parasitologi.settings' => 'Can manage pages settings in admin area',
    'kemavet.view' => 'Can view pages details',
    'kemavet.create' => 'Can create new pages',
    'kemavet.edit' => 'Can edit existing pages',
    'kemavet.delete' => 'Can delete existing pages',
    'kemavet.settings' => 'Can manage pages settings in admin area',
    'bioteknologi.view' => 'Can view pages details',
    'bioteknologi.create' => 'Can create new pages',
    'bioteknologi.edit' => 'Can edit existing pages',
    'bioteknologi.delete' => 'Can delete existing pages',
    'bioteknologi.settings' => 'Can manage pages settings in admin area',
    'epidimiologi.view' => 'Can view pages details',
    'epidimiologi.create' => 'Can create new pages',
    'epidimiologi.edit' => 'Can edit existing pages',
    'epidimiologi.delete' => 'Can delete existing pages',
    'epidimiologi.settings' => 'Can manage pages settings in admin area',
    'bakteriologi.view' => 'Can view pages details',
    'bakteriologi.create' => 'Can create new pages',
    'bakteriologi.edit' => 'Can edit existing pages',
    'bakteriologi.delete' => 'Can delete existing pages',
    'bakteriologi.settings' => 'Can manage pages settings in admin area',
    'instalasi.view' => 'Can view pages details',
    'instalasi.create' => 'Can create new pages',
    'instalasi.edit' => 'Can edit existing pages',
    'instalasi.delete' => 'Can delete existing pages',
    'instalasi.settings' => 'Can manage pages settings in admin area',

    'rencanakerja.view' => 'Can view pages details',
    'rencanakerja.create' => 'Can create new pages',
    'rencanakerja.edit' => 'Can edit existing pages',
    'rencanakerja.delete' => 'Can delete existing pages',
    'rencanakerja.settings' => 'Can manage pages settings in admin area',
    'anggaran.view' => 'Can view pages details',
    'anggaran.create' => 'Can create new pages',
    'anggaran.edit' => 'Can edit existing pages',
    'anggaran.delete' => 'Can delete existing pages',
    'anggaran.settings' => 'Can manage pages settings in admin area',
    'kinerja.view' => 'Can view pages details',
    'kinerja.create' => 'Can create new pages',
    'kinerja.edit' => 'Can edit existing pages',
    'kinerja.delete' => 'Can delete existing pages',
    'kinerja.settings' => 'Can manage pages settings in admin area',

    'berita.view' => 'Can view pages details',
    'berita.create' => 'Can create new pages',
    'berita.edit' => 'Can edit existing pages',
    'berita.delete' => 'Can delete existing pages',
    'berita.settings' => 'Can manage pages settings in admin area',
    'publikasi.view' => 'Can view pages details',
    'publikasi.create' => 'Can create new pages',
    'publikasi.edit' => 'Can edit existing pages',
    'publikasi.delete' => 'Can delete existing pages',
    'publikasi.settings' => 'Can manage pages settings in admin area',
    'pengumuman.view' => 'Can view pages details',
    'pengumuman.create' => 'Can create new pages',
    'pengumuman.edit' => 'Can edit existing pages',
    'pengumuman.delete' => 'Can delete existing pages',
    'pengumuman.settings' => 'Can manage pages settings in admin area',
    'sop.view' => 'Can view pages details',
    'sop.create' => 'Can create new pages',
    'sop.edit' => 'Can edit existing pages',
    'sop.delete' => 'Can delete existing pages',
    'sop.settings' => 'Can manage pages settings in admin area',
    'pelayanan.view' => 'Can view pages details',
    'pelayanan.create' => 'Can create new pages',
    'pelayanan.edit' => 'Can edit existing pages',
    'pelayanan.delete' => 'Can delete existing pages',
    'pelayanan.settings' => 'Can manage pages settings in admin area',
    'gallery.view' => 'Can view pages details',
    'gallery.create' => 'Can create new pages',
    'gallery.edit' => 'Can edit existing pages',
    'gallery.delete' => 'Can delete existing pages',
    'gallery.settings' => 'Can manage pages settings in admin area',
    'agenda.view' => 'Can view pages details',
    'agenda.create' => 'Can create new pages',
    'agenda.edit' => 'Can edit existing pages',
    'agenda.delete' => 'Can delete existing pages',
    'agenda.settings' => 'Can manage pages settings in admin area',
    'internallink.view' => 'Can view pages details',
    'internallink.create' => 'Can create new pages',
    'internallink.edit' => 'Can edit existing pages',
    'internallink.delete' => 'Can delete existing pages',
    'internallink.settings' => 'Can manage pages settings in admin area',
    'externallink.view' => 'Can view pages details',
    'externallink.create' => 'Can create new pages',
    'externallink.edit' => 'Can edit existing pages',
    'externallink.delete' => 'Can delete existing pages',
    'externallink.settings' => 'Can manage pages settings in admin area',
    'standarpelayanan.view' => 'Can view pages details',
    'standarpelayanan.create' => 'Can create new pages',
    'standarpelayanan.edit' => 'Can edit existing pages',
    'standarpelayanan.delete' => 'Can delete existing pages',
    'standarpelayanan.settings' => 'Can manage pages settings in admin area',
    'aplikasi.view' => 'Can view pages details',
    'aplikasi.create' => 'Can create new pages',
    'aplikasi.edit' => 'Can edit existing pages',
    'aplikasi.delete' => 'Can delete existing pages',
    'aplikasi.settings' => 'Can manage pages settings in admin area',
    'layananppid.view' => 'Can view pages details',
    'layananppid.create' => 'Can create new pages',
    'layananppid.edit' => 'Can edit existing pages',
    'layananppid.delete' => 'Can delete existing pages',
    'layananppid.settings' => 'Can manage pages settings in admin area',
    'tarifpengujian.view' => 'Can view pages details',
    'tarifpengujian.create' => 'Can create new pages',
    'tarifpengujian.edit' => 'Can edit existing pages',
    'tarifpengujian.delete' => 'Can delete existing pages',
    'tarifpengujian.settings' => 'Can manage pages settings in admin area',
    'tatacara.view' => 'Can view pages details',
    'tatacara.create' => 'Can create new pages',
    'tatacara.edit' => 'Can edit existing pages',
    'tatacara.delete' => 'Can delete existing pages',
    'tatacara.settings' => 'Can manage pages settings in admin area',
    'alurpersyaratan.view' => 'Can view pages details',
    'alurpersyaratan.create' => 'Can create new pages',
    'alurpersyaratan.edit' => 'Can edit existing pages',
    'alurpersyaratan.delete' => 'Can delete existing pages',
    'alurpersyaratan.settings' => 'Can manage pages settings in admin area',
    'mekanismepengaduan.view' => 'Can view pages details',
    'mekanismepengaduan.create' => 'Can create new pages',
    'mekanismepengaduan.edit' => 'Can edit existing pages',
    'mekanismepengaduan.delete' => 'Can delete existing pages',
    'mekanismepengaduan.settings' => 'Can manage pages settings in admin area',
    'informasiberkala.view' => 'Can view pages details',
    'informasiberkala.create' => 'Can create new pages',
    'informasiberkala.edit' => 'Can edit existing pages',
    'informasiberkala.delete' => 'Can delete existing pages',
    'informasiberkala.settings' => 'Can manage pages settings in admin area',
    'informasisetiap.view' => 'Can view pages details',
    'informasisetiap.create' => 'Can create new pages',
    'informasisetiap.edit' => 'Can edit existing pages',
    'informasisetiap.delete' => 'Can delete existing pages',
    'informasisetiap.settings' => 'Can manage pages settings in admin area',
    'informasiserta.view' => 'Can view pages details',
    'informasiserta.create' => 'Can create new pages',
    'informasiserta.edit' => 'Can edit existing pages',
    'informasiserta.delete' => 'Can delete existing pages',
    'informasiserta.settings' => 'Can manage pages settings in admin area',
    'laporanikm.view' => 'Can view pages details',
    'laporanikm.create' => 'Can create new pages',
    'laporanikm.edit' => 'Can edit existing pages',
    'laporanikm.delete' => 'Can delete existing pages',
    'laporanikm.settings' => 'Can manage pages settings in admin area',
    'pantaupenyakit.view' => 'Can view pages details',
    'pantaupenyakit.create' => 'Can create new pages',
    'pantaupenyakit.edit' => 'Can edit existing pages',
    'pantaupenyakit.delete' => 'Can delete existing pages',
    'pantaupenyakit.settings' => 'Can manage pages settings in admin area',
    'formikm.view' => 'Can view pages details',
    'formikm.create' => 'Can create new pages',
    'formikm.edit' => 'Can edit existing pages',
    'formikm.delete' => 'Can delete existing pages',
    'formikm.settings' => 'Can manage pages settings in admin area',
    'pengaduanmasyarakat.view' => 'Can view pages details',
    'pengaduanmasyarakat.create' => 'Can create new pages',
    'pengaduanmasyarakat.edit' => 'Can edit existing pages',
    'pengaduanmasyarakat.delete' => 'Can delete existing pages',
    'pengaduanmasyarakat.settings' => 'Can manage pages settings in admin area',
    'pustakaonline.view' => 'Can view pages details',
    'pustakaonline.create' => 'Can create new pages',
    'pustakaonline.edit' => 'Can edit existing pages',
    'pustakaonline.delete' => 'Can delete existing pages',
    'pustakaonline.settings' => 'Can manage pages settings in admin area',
    'sertifikathasil.view' => 'Can view pages details',
    'sertifikathasil.create' => 'Can create new pages',
    'sertifikathasil.edit' => 'Can edit existing pages',
    'sertifikathasil.delete' => 'Can delete existing pages',
    'sertifikathasil.settings' => 'Can manage pages settings in admin area',
  ];

  /**
   * --------------------------------------------------------------------
   * Permissions Matrix
   * --------------------------------------------------------------------
   * Maps permissions to groups.
   */
  public array $matrix = [
    'superadmin' => [
      'admin.*',
      'groups.*',
      'users.*',
      'beta.*',
      'widgets.*',
      'consent.*',
      'recycler.*',
      'site.*',
      'logs.*',
      'me.*',

      'blogs.*',
      'pages.*',
      'downloads.*',
      'galleries.*',
      'sejarah.*',
      'visimisi.*',
      'motto.*',
      'prestasi.*',
      'tupoksi.*',
      'alurpelayanan.*',
      'maklumatpelayanan.*',
      'komitmenbersama.*',
      'kebijakanmutu.*',
      'komitmenketerbukaan.*',
      'standarmutu.*',
      'datapegawai.*',
      'pejabatstruktural.*',
      'strukturorganisasi.*',

      'patologi.*',
      'virologi.*',
      'parasitologi.*',
      'kemavet.*',
      'bioteknologi.*',
      'epidimiologi.*',
      'bakteriologi.*',
      'instalasi.*',

      'rencanakerja.*',
      'anggaran.*',
      'kinerja.*',
      'berita.*',
      'publikasi.*',
      'pengumuman.*',
      'sop.*',
      'pelayanan.*',
      'gallery.*',
      'agenda.*',
      'internallink.*',
      'externallink.*',
      'standarpelayanan.*',
      'aplikasi.*',
      'layananppid.*',
      'tarifpengujian.*',
      'tatacara.*',
      'alurpersyaratan.*',
      'mekanismepengaduan.*',
      'informasiberkala.*',
      'informasisetiap.*',
      'informasiserta.*',
      'laporanikm.*',
      'pantaupenyakit.*',
      'formikm.*',
      'pengaduanmasyarakat.*',
      'pustakaonline.*',
      'sertifikathasil.*',
    ],
    'admin' => [
      'admin.access',
      'users.list',
      'users.create',
      'users.edit',
      'users.delete',
      'users.settings',
      'groups.settings',
      'beta.access',
      'widgets.*',
      'consent.*',
      'logs.view',
      'me.*',
    ],
    'developer' => [
      'admin.access',
      'admin.settings',
      'users.list',
      'users.create',
      'users.edit',
      'users.settings',
      'groups.settings',
      'beta.*',
      'site.viewOffline',
      'widgets.*',
      'consent.*',
      'recycler.*',
      'logs.*',
      'me.edit',
      'me.security',
    ],
    'user' => [],
    'beta' => [
      'beta.access',
    ],
  ];
}
